### ISSUE TITLE
[flaky tests] test_100_run_android_break_and_fix_app fails on Api28 emulator

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-tooling-qa#303]
Error Message
```
taps left NOT found on Emulator-Api28-Google.
```

Stacktrace
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nsbuilduser/workspace/rc-cli-run-linux/tests/cli/run/tests/run_tests.py", line 79, in test_100_run_android_break_and_fix_app
    result = run_hello_world_js_ts(self.app_name, Platform.ANDROID, self.emu)
  File "/home/nsbuilduser/workspace/rc-cli-run-linux/data/sync/hello_world_js.py", line 48, in run_hello_world_js_ts
    device.wait_for_text(text=Changes.JSHelloWord.JS.old_text)
  File "/home/nsbuilduser/workspace/rc-cli-run-linux/core/utils/device/device.py", line 102, in wait_for_text
    assert found, error_msg
AssertionError: taps left NOT found on Emulator-Api28-Google.
```

Standard Output
```
11:48:25 =============================================================
11:48:25 START TEST:  test_100_run_android_break_and_fix_app
11:48:25 
11:48:25 Kill tns processes.
11:48:25 Kill gradle processes.
11:48:25 Open home screen of emulator-5566.
11:48:25 The logcat on emulator-5566 is cleared.
11:48:25 Copy /home/nsbuilduser/workspace/rc-cli-run-linux/data/temp/TestApp/app to /home/nsbuilduser/workspace/rc-cli-run-linux/TestApp/app
11:48:25 Execute command: /home/nsbuilduser/workspace/rc-cli-run-linux/node_modules/.bin/tns run android --path TestApp --emulator >> /home/nsbuilduser/workspace/rc-cli-run-linux/out/logs/command_2019_08_09_11_48_25_694844.txt 2>&1 &
11:48:26 OUTPUT REDIRECTED: /home/nsbuilduser/workspace/rc-cli-run-linux/out/logs/command_2019_08_09_11_48_25_694844.txt

11:48:36 Can not define if app should be restarted or not.
11:50:42 'Successfully synced application org.nativescript.TestApp on device' found.
11:50:42 All items found
11:50:48 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:50:53 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:50:56 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:00 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:03 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:07 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:10 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:13 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:17 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:20 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:23 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:27 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:30 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:33 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:36 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:40 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:43 taps left NOT found on Emulator-Api28-Google. Waiting ...
11:51:45 Current text: 
11:51 & @ vat
System Ul isn't responding
x Close app
© wait
```

**Comment by dtopuzov** [comment]
Might be useful: 
https://stackoverflow.com/questions/40740367/pixel-launcher-keeps-stopping-issue-in-android-7-1-1-api-25-emulator
